DROP TABLE IF EXISTS d_ah_news, d_ah_news_categories;

CREATE TABLE `d_ah_news` (
  ID             INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  CATEGORY_ID    INT,
  DATE_CREATE    DATETIME,
  CREATED_BY     INT,
  MODIFIED_BY    INT,
  TITLE          VARCHAR(255),
  TEXT           LONGTEXT,
  TEXT_TEXT_TYPE VARCHAR(255),
  SOURCE         VARCHAR(255),
  IMAGE          INT
);

CREATE TABLE d_ah_news_categories (
  ID          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DATE_CREATE DATETIME,
  CREATED_BY  INT,
  MODIFIED_BY INT,
  TITLE       VARCHAR(255)
);